### ISSUE TITLE
Updates in Linear Regression Section

### ISSUE THREAD

**Issue by AM1CODES** [OneStep-elecTRON/onestep-electron.github.io#31]
There was a update to the linear regression section in the content repo but the changes aren't live on the website yet so please take a look into that and try and update is asap @smitbarmase @mizanxali 

Thank you.

**Comment by smitbarmase** [comment]
I will update it by today.

**Comment by AM1CODES** [comment]
Okay

**Comment by smitbarmase** [comment]
Updated Linear Regression. [Check Here](https://onestep-electron.github.io/docs/EasyTrack/linear-regression).
